services:
  - type: web
    name: dazibao-video-render
    env: docker
    plan: starter
    envVars:
      - key: RENDER_API_KEY
        value: "123456"
      - key: MAX_INPUT_MB
        value: "300"
      - key: FFMPEG_PRESET
        value: "veryfast"
      - key: FFMPEG_CRF
        value: "23"
